name = "AdventOfCode2024"
uuid = "6c467e7a-39be-4d78-92ea-edd0ecf19d84"
authors = ["Fabian Gittins <f.w.r.gittins@uu.nl>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
