name = "AdventOfCode2024"
uuid = "6c467e7a-39be-4d78-92ea-edd0ecf19d84"
authors = ["Fabian Gittins <f.w.r.gittins@uu.nl>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
